const mongoose = require('mongoose')

const depollSchema = mongoose.Schema({
  createdAt: {
    type: Date,
    immutable: true,
    required: true,
    default: () => Date.now(),
  },
  updatedAt: {
    type: Date,
    required: true,
    default: () => Date.now(),
  },
  relecture: { type: Boolean, required: true, default: false },
  lieu: { type: String, required: true },
  ville: { type: String },
  dateEvenement: { type: Date, required: true },
  dureeEvenement: { type: Number, required: true },
  latitude: { type: Number, required: true },
  longitude: { type: Number, required: true },
  pays: String,
  nombreParticipantsWings: Number,
  nombreParticipantsExterne: Number,
  crewId: [
    {
      type: mongoose.Types.ObjectId,
      required: true,
      ref: 'Crew',
    },
  ],
  autresStructures: [String],
  longueur: Number,
  surface: { type: Number, required: true },
  typeLieu: { type: String, required: true },
  typesDechet: [String],
  activites: [String],
  frequentation: String,
  quantiteDechet: String,
  pourquoiIlEnReste: [String],
  commentaire: String,
  poidsPlastiqueNonRecy: Number,
  volumePlastiqueNonRecy: Number,
  poidsPlastiqueRecy: Number,
  volumePlastiqueRecy: Number,
  poidsMetal: Number,
  volumeMetal: Number,
  poidsVerreEtCeramique: Number,
  volumeVerreEtCeramique: Number,
  poidsTextile: Number,
  volumeTextile: Number,
  poidsPapierEtCarton: Number,
  volumePapierEtCarton: Number,
  poidsBois: Number,
  volumeBois: Number,
  poidsCaoutchouc: Number,
  volumeCaoutchouc: Number,
  poidsAutre: Number,
  volumeAutre: Number,
  bouteilleEnPlastique: Number,
  bouteilleEnVerre: Number,
  canetteEnMetal: Number,
  masque: Number,
  megot: Number,
  pneu: Number,
  appareilMenager: Number,
  ballonDeBaudruche: Number,
  batonDeSucette: Number,
  batterie: Number,
  boiteDAppats: Number,
  boiteDeMedicaments: Number,
  bouchonEnPlastique: Number,
  briquet: Number,
  capsule: Number,
  cartoucheDeChasse: Number,
  chaussure: Number,
  contenantAlimentaire: Number,
  cordagesEmmeles: Number,
  cordageEtFicelle: Number,
  cotonTige: Number,
  filetInf50cm: Number,
  filetSup50cm: Number,
  gobelet: Number,
  jouetEnPlastique: Number,
  materielDePeche: Number,
  mediaFiltrant: Number,
  mousse: Number,
  pailleEnPlastique: Number,
  protectionHygienique: Number,
  sacPlastique: Number,
  vaisselleEnPlastique: Number,
  vetement: Number,
  dechetSpecifique: [
    {
      type: mongoose.Types.ObjectId,
      ref: 'DechetSpecifique',
    },
  ],
})

depollSchema.pre('save', function (next) {
  this.updatedAt = Date.now()
  next()
})

module.exports = mongoose.model('Depoll', depollSchema, 'depoll')
