let mongoose = require('mongoose');

const depollSchema = mongoose.Schema({
  createdTime: { type: Date, required: true },
  lieu: { type: String, required: true },
  ville: { type: String},
  dateEvenement: { type: Date, required: true },
  dureeEvenement: { type: Number, required: true },
  nombreParticipantsWings: Number,
  nombreParticipantsExterne: Number,
  crew: String,
  autresStructures: String,
  longueur: Number,
  surface: Number,
  typeLieu: String,
  typesDechet: String,
  activites: String,
  frequentation: String,
  quantiteDechet: String,
  pourquoiIlEnReste: String,
  Commentaire: String,
  poidsPlastiqueNonRecy: Number,
  volumePlastiqueNonRecy: Number,
  poidsPlastiqueRecy: Number,
  volumePlastiqueRecy: Number,
  poidsMetal: Number,
  volumeMetal: Number,
  poidsVerreEtCeramique: Number,
  volumeVerreEtCeramique: Number,
  poidsTextile: Number,
  volumeTextile: Number,
  poidsPapierEtCarton: Number,
  volumePapierEtCarton: Number,
  poidsBois: Number,
  volumeBois: Number,
  poidsCaoutchouc: Number,
  volumeCaoutchouc: Number,
  poidsAutre: Number,
  volumeAutre: Number,
});

module.exports = mongoose.model('Depoll', depollSchema);
